plugins:
  - "scratchpads"
  - "expose"
  - "float"
  - "monitors"

options:
  bring_float:
    offset: 0.01

  scratchpads:
    - term:
        command: "alacritty --class gophrland-alacritty"
        animation: "fromTop"
        unfocus: "hide"
        margin: 60

    - volume:
        command: "alacritty --class pulsemixer-alacritty -e pulsemixer"
        animation: "fromRight"
        unfocus: "hide"
        margin: 50

    - slack:
        command: "slack"
        animation: "fromRight"
        class: "Slack"
        margin: 60

    - whatsdesk:
        command: "whatsdesk"
        animation: "fromBottom"
        class: "whatsdesk"
        margin: 40

    # - cava:
    #     command: "alacritty --class cava-alacritty -e cava"
    #     animation: "fromBottom"
    #     margin: 10
