plugins:
  - "scratchpads"
  - "expose"
  - "float"
  - "monitors"

options:
  float:
    offset: 0.01

  scratchpads:
    - term:
        command: "alacritty --class gophrland-alacritty"
        floatOpts:
          animation: "fromTop"
          margin: 60
        float: true
        unfocus: "hide"

    - volume:
        command: "alacritty --class pulsemixer-alacritty -e pulsemixer"
        float: true
        floatOpts:
          animation: "fromRight"
          margin: 50
        unfocus: "hide"

    - slack:
        command: "slack"
        class: "Slack"
        float: false

    - whatsdesk:
        command: "whatsdesk"
        class: "whatsdesk"
        float: false
